//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Merchants = newMerchantsTable("public", "merchants", "")

type merchantsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	MechantName postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type MerchantsTable struct {
	merchantsTable

	EXCLUDED merchantsTable
}

// AS creates new MerchantsTable with assigned alias
func (a MerchantsTable) AS(alias string) *MerchantsTable {
	return newMerchantsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MerchantsTable with assigned schema name
func (a MerchantsTable) FromSchema(schemaName string) *MerchantsTable {
	return newMerchantsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MerchantsTable with assigned table prefix
func (a MerchantsTable) WithPrefix(prefix string) *MerchantsTable {
	return newMerchantsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MerchantsTable with assigned table suffix
func (a MerchantsTable) WithSuffix(suffix string) *MerchantsTable {
	return newMerchantsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMerchantsTable(schemaName, tableName, alias string) *MerchantsTable {
	return &MerchantsTable{
		merchantsTable: newMerchantsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newMerchantsTableImpl("", "excluded", ""),
	}
}

func newMerchantsTableImpl(schemaName, tableName, alias string) merchantsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		MechantNameColumn = postgres.StringColumn("mechant_name")
		allColumns        = postgres.ColumnList{IDColumn, MechantNameColumn}
		mutableColumns    = postgres.ColumnList{MechantNameColumn}
		defaultColumns    = postgres.ColumnList{}
	)

	return merchantsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		MechantName: MechantNameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
