//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Offers = newOffersTable("public", "offers", "")

type offersTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	MerchantID      postgres.ColumnString
	Active          postgres.ColumnBool
	MinTransactions postgres.ColumnInteger
	LookbackDays    postgres.ColumnInteger
	StartDate       postgres.ColumnTimestampz
	EndDate         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type OffersTable struct {
	offersTable

	EXCLUDED offersTable
}

// AS creates new OffersTable with assigned alias
func (a OffersTable) AS(alias string) *OffersTable {
	return newOffersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OffersTable with assigned schema name
func (a OffersTable) FromSchema(schemaName string) *OffersTable {
	return newOffersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OffersTable with assigned table prefix
func (a OffersTable) WithPrefix(prefix string) *OffersTable {
	return newOffersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OffersTable with assigned table suffix
func (a OffersTable) WithSuffix(suffix string) *OffersTable {
	return newOffersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOffersTable(schemaName, tableName, alias string) *OffersTable {
	return &OffersTable{
		offersTable: newOffersTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newOffersTableImpl("", "excluded", ""),
	}
}

func newOffersTableImpl(schemaName, tableName, alias string) offersTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		MerchantIDColumn      = postgres.StringColumn("merchant_id")
		ActiveColumn          = postgres.BoolColumn("active")
		MinTransactionsColumn = postgres.IntegerColumn("min_transactions")
		LookbackDaysColumn    = postgres.IntegerColumn("lookback_days")
		StartDateColumn       = postgres.TimestampzColumn("start_date")
		EndDateColumn         = postgres.TimestampzColumn("end_date")
		allColumns            = postgres.ColumnList{IDColumn, MerchantIDColumn, ActiveColumn, MinTransactionsColumn, LookbackDaysColumn, StartDateColumn, EndDateColumn}
		mutableColumns        = postgres.ColumnList{MerchantIDColumn, ActiveColumn, MinTransactionsColumn, LookbackDaysColumn, StartDateColumn, EndDateColumn}
		defaultColumns        = postgres.ColumnList{ActiveColumn}
	)

	return offersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		MerchantID:      MerchantIDColumn,
		Active:          ActiveColumn,
		MinTransactions: MinTransactionsColumn,
		LookbackDays:    LookbackDaysColumn,
		StartDate:       StartDateColumn,
		EndDate:         EndDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
