//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var OffersMccs = newOffersMccsTable("public", "offers_mccs", "")

type offersMccsTable struct {
	postgres.Table

	// Columns
	OfferID postgres.ColumnString
	Mcc     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type OffersMccsTable struct {
	offersMccsTable

	EXCLUDED offersMccsTable
}

// AS creates new OffersMccsTable with assigned alias
func (a OffersMccsTable) AS(alias string) *OffersMccsTable {
	return newOffersMccsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OffersMccsTable with assigned schema name
func (a OffersMccsTable) FromSchema(schemaName string) *OffersMccsTable {
	return newOffersMccsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OffersMccsTable with assigned table prefix
func (a OffersMccsTable) WithPrefix(prefix string) *OffersMccsTable {
	return newOffersMccsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OffersMccsTable with assigned table suffix
func (a OffersMccsTable) WithSuffix(suffix string) *OffersMccsTable {
	return newOffersMccsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOffersMccsTable(schemaName, tableName, alias string) *OffersMccsTable {
	return &OffersMccsTable{
		offersMccsTable: newOffersMccsTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newOffersMccsTableImpl("", "excluded", ""),
	}
}

func newOffersMccsTableImpl(schemaName, tableName, alias string) offersMccsTable {
	var (
		OfferIDColumn  = postgres.StringColumn("offer_id")
		MccColumn      = postgres.StringColumn("mcc")
		allColumns     = postgres.ColumnList{OfferIDColumn, MccColumn}
		mutableColumns = postgres.ColumnList{}
		defaultColumns = postgres.ColumnList{}
	)

	return offersMccsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		OfferID: OfferIDColumn,
		Mcc:     MccColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
