//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Transactions = newTransactionsTable("public", "transactions", "")

type transactionsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	MerchantID  postgres.ColumnString
	UserID      postgres.ColumnString
	Mcc         postgres.ColumnString
	AmountCents postgres.ColumnInteger
	ApprovedAt  postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TransactionsTable struct {
	transactionsTable

	EXCLUDED transactionsTable
}

// AS creates new TransactionsTable with assigned alias
func (a TransactionsTable) AS(alias string) *TransactionsTable {
	return newTransactionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TransactionsTable with assigned schema name
func (a TransactionsTable) FromSchema(schemaName string) *TransactionsTable {
	return newTransactionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TransactionsTable with assigned table prefix
func (a TransactionsTable) WithPrefix(prefix string) *TransactionsTable {
	return newTransactionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TransactionsTable with assigned table suffix
func (a TransactionsTable) WithSuffix(suffix string) *TransactionsTable {
	return newTransactionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTransactionsTable(schemaName, tableName, alias string) *TransactionsTable {
	return &TransactionsTable{
		transactionsTable: newTransactionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newTransactionsTableImpl("", "excluded", ""),
	}
}

func newTransactionsTableImpl(schemaName, tableName, alias string) transactionsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		MerchantIDColumn  = postgres.StringColumn("merchant_id")
		UserIDColumn      = postgres.StringColumn("user_id")
		MccColumn         = postgres.StringColumn("mcc")
		AmountCentsColumn = postgres.IntegerColumn("amount_cents")
		ApprovedAtColumn  = postgres.TimestampzColumn("approved_at")
		allColumns        = postgres.ColumnList{IDColumn, MerchantIDColumn, UserIDColumn, MccColumn, AmountCentsColumn, ApprovedAtColumn}
		mutableColumns    = postgres.ColumnList{MerchantIDColumn, UserIDColumn, MccColumn, AmountCentsColumn, ApprovedAtColumn}
		defaultColumns    = postgres.ColumnList{}
	)

	return transactionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		MerchantID:  MerchantIDColumn,
		UserID:      UserIDColumn,
		Mcc:         MccColumn,
		AmountCents: AmountCentsColumn,
		ApprovedAt:  ApprovedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
