// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/api/server.go
//
// Generated by this command:
//
//	mockgen -source=./internal/api/server.go -destination=./internal/api/mocks.go -package=api
//

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	core "github.com/lualfe/offer-eligibility-api/internal/core"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateOffer mocks base method.
func (m *MockService) CreateOffer(ctx context.Context, req core.CreateOfferRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOffer", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOffer indicates an expected call of CreateOffer.
func (mr *MockServiceMockRecorder) CreateOffer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOffer", reflect.TypeOf((*MockService)(nil).CreateOffer), ctx, req)
}

// CreateTransactions mocks base method.
func (m *MockService) CreateTransactions(ctx context.Context, req core.CreateTransactionsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactions", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransactions indicates an expected call of CreateTransactions.
func (mr *MockServiceMockRecorder) CreateTransactions(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactions", reflect.TypeOf((*MockService)(nil).CreateTransactions), ctx, req)
}

// GetEligibleOffers mocks base method.
func (m *MockService) GetEligibleOffers(ctx context.Context, req core.GetEligibleOffersRequest) (core.EligibleOffers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEligibleOffers", ctx, req)
	ret0, _ := ret[0].(core.EligibleOffers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEligibleOffers indicates an expected call of GetEligibleOffers.
func (mr *MockServiceMockRecorder) GetEligibleOffers(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEligibleOffers", reflect.TypeOf((*MockService)(nil).GetEligibleOffers), ctx, req)
}
