//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Offers struct {
	ID              uuid.UUID `sql:"primary_key"`
	MerchantID      uuid.UUID
	Active          bool
	MinTransactions int16
	LookbackDays    int16
	StartDate       time.Time
	EndDate         time.Time
}
