//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Transactions struct {
	ID          uuid.UUID `sql:"primary_key"`
	MerchantID  uuid.UUID
	UserID      uuid.UUID
	Mcc         string
	AmountCents int32
	ApprovedAt  time.Time
}
