// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/core/service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/core/service.go -destination=./internal/core/mocks.go -package=core
//

// Package core is a generated GoMock package.
package core

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateOffer mocks base method.
func (m *MockRepository) CreateOffer(ctx context.Context, req CreateOfferRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOffer", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOffer indicates an expected call of CreateOffer.
func (mr *MockRepositoryMockRecorder) CreateOffer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOffer", reflect.TypeOf((*MockRepository)(nil).CreateOffer), ctx, req)
}

// CreateTransactions mocks base method.
func (m *MockRepository) CreateTransactions(ctx context.Context, req CreateTransactionsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactions", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransactions indicates an expected call of CreateTransactions.
func (mr *MockRepositoryMockRecorder) CreateTransactions(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactions", reflect.TypeOf((*MockRepository)(nil).CreateTransactions), ctx, req)
}

// GetEligibleOffers mocks base method.
func (m *MockRepository) GetEligibleOffers(ctx context.Context, req GetEligibleOffersRequest) (EligibleOffers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEligibleOffers", ctx, req)
	ret0, _ := ret[0].(EligibleOffers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEligibleOffers indicates an expected call of GetEligibleOffers.
func (mr *MockRepositoryMockRecorder) GetEligibleOffers(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEligibleOffers", reflect.TypeOf((*MockRepository)(nil).GetEligibleOffers), ctx, req)
}
